host: "localhost:8080"
info:
    title: "VK Film API"
    description: |
        This API provides endpoints for managing movies and actors.

        To test administrator endpoints, you can use the following credentials:
        Username: vk-admin
        Password: vk-password
schemes:
    - http
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
        description: enter the token with the Bearer prefix e.g. Bearer eyJhbGci...
definitions:
    user:
        properties:
            created_at:
                description: The timestamp when the user was created.
                example: '"2022-03-17T09:00:00Z"'
                format: date-time
                type: string
            password_changed_at:
                description: The timestamp when the password was last changed.
                example: '"2022-03-17T10:00:00Z"'
                format: date-time
                type: string
            role:
                description: The role of the user.
                example: administrator
                type: string
            username:
                description: The username of the user.
                example: vk-user
                type: string
        title: userResponse represents the response body for a user.
        type: object
    actor:
        title: actorResponse represents the response body for an actor.
        type: object
        properties:
            birthday:
                description: The birthday of the actor.
                example: "2000-01-01T00:00:00Z"
                format: date-time
                type: string
            gender:
                description: 'The gender of the actor, can be: ["male", "female", "other"].'
                example: male
                type: string
            id:
                description: The ID of the actor.
                example: 1
                format: int32
                type: integer
            name:
                description: The name of the actor.
                example: Leonardo Di Caprio
                type: string
    actorsWithMovies:
        type: array
        items:
            type: object
            properties:
                id:
                    type: integer
                    format: int32
                    example: 1
                name:
                    type: string
                    example: Leonardo Di Caprio
                    description: The name of the actor.
                gender:
                    type: string
                    example: male
                    description: The gender of the actor.
                birthday:
                    type: string
                    example: "2000-01-01T00:00:00Z"
                    description: The birthday of the actor.
                movies:
                    type: array
                    items:
                        $ref: '#/definitions/movie'

        title: allActorsResponse represents the response body for all actors.

    actorRequest:
        type: object
        title: actorRequest represents the request body for an actor.
        properties:
            name:
                description: The name of the actor.
                example: Leonardo Di Caprio
                type: string
            birthday:
                description: The birthday of the actor.
                example: "2000-01-01T00:00:00Z"
                format: date-time
                type: string
            gender:
                description: 'The gender of the actor, can be: ["male", "female", "other"].'
                example: male
                type: string
    userRequest:
        type: object
        required: 
            - username
            - password
        properties:
            username:
                description: The username of the user.
                example: vk-user
                type: string
            password:
                description: The password of the user.
                example: password
                type: string
    movie:
        properties:
            description:
                description: The description of the movie.
                example: A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.
                type: string
            id:
                description: The ID of the movie.
                example: 123
                format: int32
                type: integer
            name:
                description: The name of the movie.
                example: The Matrix
                type: string
            rating:
                description: The rating of the movie.
                example: "8.7"
                type: string
            release_date:
                description: The release date of the movie.
                example: "2012-07-16T00:00:00Z"
                format: date-time
                type: string
        type: object
        title: movieResponse represents the response for a movie.
    allMovies:
        type: array
        items:
            $ref: '#/definitions/movie'
        title: allMoviesResponse represents the response body for all movies.

    deleteMovieRequest:
        type: object
        required:
            - id
        properties:
            id:
             description: The ID of the movie to be deleted.
             example: 123
             format: int32
             type: integer
        title: deleteMovieRequest represents the request body for deleting a movie.


    createMovieRequest:
        type: object
        required: 
            - name
            - description
            - release_date
            - rating
        properties:
            name:
                description: The name of the movie.
                example: Inception
                type: string
            description:
                description: The description of the movie.
                example: A mind-bending action thriller
                type: string
            release_date:
                description: The release date of the movie.
                format: date
                example: "2012-07-16T00:00:00Z"
            rating:
                description: The rating of the movie.
                example: "8.8"
                type: string
        title: userRequest represents the request body for a user.
info: {}
paths:
    /users:
        post:

            operationId: createUser
            consumes:
                - application/json
            operationId: createUser
            summary: Creates a new user.
            parameters:
                - in: body
                  name: user
                  description: The user to create.
                  schema:
                    $ref: '#/definitions/userRequest'
            produces:
                - application/json
            tags:
                - users
            responses:
                200:
                    $ref: '#/responses/userResponse'
                400:
                    $ref: '#/responses/error400Response'
                401:
                    $ref: '#/responses/error401Response'
                403:
                    $ref: '#/responses/error403Response'
                500:
                    $ref: '#/responses/error500Response'
    /users/login:
        post:
            operationId: loginUser
            summary: Logs in a user.
            parameters:
                - in: body
                  name: user
                  description: The user to log in.
                  schema:
                    $ref: '#/definitions/userRequest'
            produces:
                - application/json
            responses:
                200:
                    $ref: '#/responses/loginUser'
                400:
                    $ref: '#/responses/error400Response'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
            tags:
                - users
    /actors:
        delete:
            security:
                - Bearer: []
            consumes: 
                - application/json
            operationId: deleteActor
            parameters: 
                - in: query
                  name: id
                  required: true
                  description: The ID of the actor to be deleted.
            produces:
                - application/json
            responses:
                200:
                    schema:
                        type: object
                        properties:
                            id:
                                type: integer
                                format: int32
                                example: 1
                400:
                    $ref: '#/responses/error400Response'
                403:
                    $ref: '#/responses/error403Response'
                404:
                    $ref: '#/responses/error404Response'
            summary: Deletes an actor by ID, ONLY FOR ADMINISTRATORS.
            tags:
                - actors
        post:
            security:
                - Bearer: []
            operationId: createActor
            parameters:
                - in: body
                  name: actor
                  schema:
                      $ref: '#/definitions/actorRequest'
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/actor'
                "400":
                    $ref: '#/responses/error400Response'
                "401":
                    $ref: '#/responses/error401Response'
                "500":
                    $ref: '#/responses/error500Response'
            summary: Creates a new actor, ONLY FOR ADMINISTRATORS.
            tags:
                - actors
        patch:
            security:
                - Bearer: []
            operationId: updateActor
            consumes:
                - application/json
            parameters:
                - in: body
                  name: actor
                  schema:
                      $ref: '#/definitions/actor'
            produces:
                - application/json
            responses:
                200:
                    $ref: '#/responses/actor'
                400:
                    $ref: '#/responses/error400Response'
                403:
                    $ref: '#/responses/error403Response'
                404:
                    $ref: '#/responses/error404Response'
                500:
                    $ref: '#/responses/error500Response'
            summary: Updates an existing actor, ONLY FOR ADMINISTRATORS.
            tags:
                - actors
    /actors-movies:
        get:
            security:
                - Bearer: []
            operationId: actorsWithMovies
            produces:
                - application/json
            summary: Gets all actors with their movies.
            tags:
                - actors
            responses:
                200:
                    $ref: '#/responses/actorsWithMovies'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'

    /movie/create:
        post:
            security:
                - Bearer: []
            operationId: createMovie
            consumes:
                - application/json
            parameters:
                - in: body
                  name: movie
                  schema:
                    $ref: '#/definitions/createMovieRequest'
            produces:
                - application/json
            summary: Creates a new movie with the provided details, ONLY FOR ADMINISTRATORS.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/movieResponse'
                400:
                    $ref: '#/responses/error400Response'
                403:
                    $ref: '#/responses/error403Response'
                404:
                    $ref: '#/responses/error404Response'
                500:
                    $ref: '#/responses/error500Response'

    /movie/delete:
        delete:
            security:
                - Bearer: []
            operationId: deleteMovie
            parameters:
                  - in: query
                    name: id
                    required: true
            produces:
                - application/json
            summary: Delete a movie with the provided ID, ONLY FOR ADMINISTRATORS.
            responses:
                200:
                    schema:
                        type: object
                        properties:
                            id:
                                type: integer
                                format: int32
                                example: 1
                400:
                    $ref: '#/responses/error400Response'
                403:
                    $ref: '#/responses/error403Response'
                404:
                    $ref: '#/responses/error404Response'
            tags:
                - movies
    /movie/update:
        patch:
            security:
                - Bearer: []
            operationId: updateMovie
            consumes:
                - application/json
            summary: Updates a movie with the provided details, ONLY FOR ADMINISTRATORS.
            parameters:
                - in: body
                  name: movie
                  schema:
                    $ref: '#/definitions/movie'
            produces:
                - application/json
            responses:
                200:
                    $ref: '#/responses/movieResponse'
                400:
                    $ref: '#/responses/error400Response'
                403:
                    $ref: '#/responses/error403Response'
                404:
                    $ref: '#/responses/error404Response'
                500:
                    $ref: '#/responses/error500Response'

            tags:
                - movies
    /movies:
        get:
            security:
                - Bearer: []
            operationId: moviesSortedByRating
            summary: Retrieves movies sorted by rating.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/allMoviesRespose'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
    /movies/by-actor-fragment:
        get:
            security:
                - Bearer: []
            consumes:
                - application/json
            operationId: moviesByActorFragment
            parameters:
                - in: query
                  name: actor
                  required: true
                  description: The actor fragment to search for.
            produces:
                - application/json
            summary: Retrieves movies by actor fragment.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/allMoviesRespose'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
    /movies/by-date:
        get:
            security:
                - Bearer: []
            operationId: moviesSortedByReleaseDate
            summary: Retrieves movies sorted by release date.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/allMoviesRespose'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
    /movies/by-name:
        get:
            security:
                - Bearer: []
            operationId: moviesSortedByName
            summary: Retrieves movies sorted by name.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/allMoviesRespose'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
    /movies/by-name-fragment:
        get:
            security:
                - Bearer: []
            consumes:
                - application/json
            operationId: moviesByNameFragment
            parameters:
                - in: query
                  name: name
                  required: true
                  description: The movie fragment to search for.
            produces:
                - application/json
            summary: Retrieves movies by name fragment.
            tags:
                - movies
            responses:
                200:
                    $ref: '#/responses/allMoviesRespose'
                401:
                    $ref: '#/responses/error401Response'
                500:
                    $ref: '#/responses/error500Response'
responses:
    actor:
        description: actorResponse represents the response body for an actor.
        properties:
            actor:
                description: The actor information.
        schema:
            $ref: '#/definitions/actor'
    actorsWithMovies:
        description: actorsWithMoviesResponse represents the response body for all actors with movies.
        properties:
            actors:
                description: The list of actors.
        schema:
            $ref: '#/definitions/actorsWithMovies'    

    loginUser:
        description: loginUserResponse represents the response body for logging in a user.
        headers:
            access_token:
                description: The access token for the user.
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im...
                type: string
        properties:
            user:
                description: The user information.
        schema:
            $ref: '#/definitions/user'
    allMoviesRespose:
        description: allMoviesResponse represents the response body for all movies.
        properties:
            movies:
                description: The list of movies.
        schema:
            $ref: '#/definitions/allMovies'

    movieResponse:
        properties:
            movie:
                description: movieResponse represents the response for a movie.
        schema:
            $ref: '#/definitions/movie'
    userResponse:
        type: object
        description: userResponse represents the response body for a user.
        properties:
            user:
                description: User Information.
        schema:
            $ref: '#/definitions/user'

    error400Response:
        description: Bad Request.
    error401Response:
        description: Unauthorized.
    error403Response:
        description: Forbidden.
    error404Response:
        description: Not Found.
    error500Response:
        description: Internal Server Error.
swagger: "2.0"
