// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Actor struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Gender   string       `json:"gender"`
	Birthday sql.NullTime `json:"birthday"`
}

type Movie struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Rating      sql.NullString `json:"rating"`
}

type MovieActor struct {
	MovieID int32 `json:"movie_id"`
	ActorID int32 `json:"actor_id"`
}
