// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: movie.sql

package db

import (
	"context"
	"database/sql"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
  name,
  description,
  release_date,
  rating
) VALUES 
  ($1, $2, $3, $4) RETURNING id, name, description, release_date, rating
`

type CreateMovieParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Rating      sql.NullString `json:"rating"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Name,
		arg.Description,
		arg.ReleaseDate,
		arg.Rating,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ReleaseDate,
		&i.Rating,
	)
	return i, err
}
