// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
